stages:
- name: build
  steps:
  - runScriptConfig:
      image: node:latest
      shellScript: npm run build
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./server/Dockerfile
      buildContext: .
      tag: dealpal/parse-server
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
